import Foundation
import Testing
@testable import CFDomain

/// Golden-master checks (plan §3 / §4-N3): the Swift segmentation must be
/// indistinguishable from the reference Python implementation.
///
/// Two legs:
/// 1. **Synthetic** — a committed fixture generated by
///    `scripts/gen_segmentation_golden.py` running the *reference*
///    `segment_words_by_silence` / `_make_clip_id` /
///    `transcript_text_for_range` over 402 seeded words (incl. exact
///    2.0s-threshold gaps and half-even-rounding .5 ms timestamps). Runs
///    everywhere.
/// 2. **Real inbox** — Swift segmentation over the web-processed sidecars
///    Lillian moved into `~/ClipFarm/Footage/` (2026-07-06), diffed against
///    the legacy `clipfarm.json` at the repo root (verified pristine: fresh
///    reference segmentation reproduces it bit-for-bit). Tail policy =
///    word-end for comparability. Skips visibly on machines without the
///    inbox material.

// MARK: - Leg 1: synthetic fixture

private struct GoldenFixture: Decodable {
    struct Case: Decodable {
        let threshold: Double
        let ranges: [[Double]]
        let clip_ids: [String]
        let texts: [String]
    }
    let stem: String
    let duration: Double
    let words: [WhisperWord]
    let cases: [Case]
}

@Test func syntheticGoldenMasterMatchesReferenceImplementation() throws {
    let url = try #require(
        Bundle.module.url(forResource: "Resources/segmentation-golden", withExtension: "json")
            ?? Bundle.module.url(forResource: "segmentation-golden", withExtension: "json")
    )
    let fixture = try JSONDecoder().decode(GoldenFixture.self, from: Data(contentsOf: url))
    let transcript = WhisperTranscript(
        schemaVersion: 1,
        duration: fixture.duration,
        segments: [WhisperSegment(id: 0, start: 0, end: fixture.duration, words: fixture.words)]
    )

    for testCase in fixture.cases {
        let ranges = try Segmentation.rangesBySilence(
            words: fixture.words, gapThresholdSec: testCase.threshold)

        #expect(ranges.count == testCase.ranges.count, "range count @ threshold \(testCase.threshold)")
        // Bit-exact range endpoints: both sides parsed the same decimal
        // JSON into IEEE doubles and did the same comparisons — no epsilon.
        #expect(ranges.map { [$0.startSec, $0.endSec] } == testCase.ranges)
        // Clip-ID encoding incl. half-even millisecond rounding.
        #expect(
            ranges.map { ClipID.make(sourceStem: fixture.stem, start: $0.startSec, end: $0.endSec) }
                == testCase.clip_ids
        )
        // Per-clip transcript text (half-open range + leading-space concat).
        #expect(
            ranges.map { transcript.transcriptText(from: $0.startSec, to: $0.endSec) }
                == testCase.texts
        )
    }
}

// MARK: - Leg 2: real inbox vs the legacy web state

private let footageInbox = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent("ClipFarm/Footage")

/// mac/ClipFarmKit/Tests/CFDomainTests/<this file> -> repo root.
private let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()  // CFDomainTests
    .deletingLastPathComponent()  // Tests
    .deletingLastPathComponent()  // ClipFarmKit
    .deletingLastPathComponent()  // mac
    .deletingLastPathComponent()  // repo root

private let goldenStems = ["btc.0.2", "btc.0.4", "freestylingbtc0"]

private var realGoldenMaterialPresent: Bool {
    FileManager.default.fileExists(atPath: repoRoot.appendingPathComponent("clipfarm.json").path)
        && goldenStems.allSatisfy {
            FileManager.default.fileExists(
                atPath: footageInbox.appendingPathComponent("\($0).whisper.json").path)
        }
}

@Test(.enabled(if: realGoldenMaterialPresent))
func realInboxSegmentationMatchesTheWebVersionsClips() throws {
    // Test-only fixture loader (D9): the legacy clipfarm.json never ships.
    let legacy = try JSONDecoder().decode(
        ClipFarmState.self,
        from: Data(contentsOf: repoRoot.appendingPathComponent("clipfarm.json"))
    )
    let sourcesByStem = Dictionary(
        uniqueKeysWithValues: legacy.sources.map { id, source -> (String, String) in
            let stem = (source.filename as NSString).deletingPathExtension
            return (stem, id)
        }
    )

    for stem in goldenStems {
        let sourceID = try #require(sourcesByStem[stem], "web state must know \(stem)")
        let sidecarURL = footageInbox.appendingPathComponent("\(stem).whisper.json")
        let transcript = try JSONDecoder().decode(
            WhisperTranscript.self, from: Data(contentsOf: sidecarURL))
        #expect(transcript.schemaVersion == 1)

        // Word-end tail policy == the web behavior (comparability, plan §4/N3).
        let ranges = try Segmentation.segment(
            words: transcript.allWords,
            gapThresholdSec: 2.0,
            tailPolicy: .wordEnd,
            tailPaddingSec: 0,
            sourceDurationSec: transcript.duration
        )
        let swiftClips = Dictionary(
            uniqueKeysWithValues: ranges.map { range in
                (
                    ClipID.make(sourceStem: stem, start: range.startSec, end: range.endSec),
                    range
                )
            }
        )
        let legacyClips = legacy.clips.filter { $0.value.sourceID == sourceID }

        #expect(swiftClips.count == legacyClips.count, "\(stem): clip count vs web")
        #expect(Set(swiftClips.keys) == Set(legacyClips.keys), "\(stem): clip IDs vs web")
        for (id, clip) in legacyClips {
            guard let range = swiftClips[id] else { continue }
            #expect(range.startSec == clip.startSec, "\(stem) \(id): start")
            #expect(range.endSec == clip.endSec, "\(stem) \(id): end")
            #expect(
                transcript.transcriptText(from: range.startSec, to: range.endSec)
                    == clip.transcriptText,
                "\(stem) \(id): transcript text"
            )
        }
    }
}
